config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :sklads do
    resources :deliveries
  end

  resources :deliveries
  resources :sklad_products
  resources :regions
  resources :products
  resources :transfers
end

app/models/sklad.rb
class Sklad < ApplicationRecord
  validates :name, uniqueness: true, presence: true

  has_many :sklad_products
  has_many :products, through: :sklad_products

  def product_quantify product_id
    product = self.sklad_products.find { |tmp| tmp.product.id == product_id }
    product.nil? ? 0 : product.quantify
  end

  def product_get product_id, quantify
    sklad_product = self.sklad_products.find_by( product_id: product_id )
    if sklad_product.nil?
      errors.add( "quantify", "Product not found" )
    else
      if sklad_product.quantify >= quantify and quantify > 0
        sklad_product.decrement('quantify', quantify)
        sklad_product.quantify <= 0 ? sklad_product.destroy! : sklad_product.save!
      else
        errors.add( "quantify", "Quantify out of stock" )
      end
    end
  end

  def product_add product_id, quantify
    sklad_product = self.sklad_products.find_by( product_id: product_id )

    if sklad_product
      sklad_product.increment!('quantify', quantify)
    else
      sklad_product = SkladProduct.new( sklad_id: self.id, product_id: product_id, quantify: quantify )
      errors.add( "quantify", "Quantify add error" ) unless sklad_product.save!
    end
  end
end

app/controllers/sklads_controller.rb
class SkladsController < ApplicationController
  before_action :set_sklad, only: [:show, :edit, :update, :destroy]
  # before_action :set_products, only: :show
  before_action :set_regions

  # GET /sklads
  def index
    @sklads = Sklad.all
  end

  # GET /sklads/1
  def show

  end

  # GET /sklads/new
  def new
    @sklad = Sklad.new
  end

  # GET /sklads/1/edit
  def edit
  end

  # POST /sklads
  def create
    @sklad = Sklad.new(sklad_params)

    if @sklad.save
      redirect_to @sklad, notice: t('sklad_created_ok')
    else
      render :new
    end
  end

  # PATCH/PUT /sklads/1
  def update
    if @sklad.update(sklad_params)
      redirect_to @sklad, notice: 'Sklad was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /sklads/1
  def destroy
    @sklad.destroy
    redirect_to sklads_url, notice: 'Sklad was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sklad
      @sklad = Sklad.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sklad_params
      params.require(:sklad).permit(:name, :region)
    end

    def set_regions
      @regions = Region.select(:name).map(&:name).uniq.sort
    end
end

app/helpers/sklads_helper.rb
module SkladsHelper
end

app/views/sklads/_form.html.haml
= form_with(model: sklad) do |form|
  - if sklad.errors.any?
    #error_explanation
      %h2
        = pluralize(sklad.errors.count, "error")
        prohibited this sklad from being saved:
      %ul
        - sklad.errors.each do |error|
          %li= error.full_message
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :region
    = form.select 'region', regions, {:prompt => t('select_region')}
  .actions
    = form.submit

app/views/sklads/_menu.html.haml
%hr
= link_to t('delivery'), new_sklad_delivery_path(@sklad), class: params[:controller]
= link_to t('history_delivery'), deliveries_url
= link_to t('transfer'), new_transfer_url
= link_to t('history_transfer'), transfers_url

app/views/sklads/_products.html.haml
%h1= t 'products'
%table
  %thead
    %tr
      %th= t 'name'
      %th= t 'quantify'
      %th= t 'last_date_delivery'
  %tbody
    - @sklad.sklad_products.each do |sklad_product|
      %tr
        %td= sklad_product.product.name
        %td= sklad_product.quantify
        %td= sklad_product.try(:delivery_last) ? l(sklad_product.delivery_last,  :format => "%d %B %Y - %H:%M") : t('not_exist_delivery')

app/views/sklads/edit.html.haml
%h1 Editing Sklad
= render 'form', sklad: @sklad
= link_to 'Show', @sklad
|
= link_to 'Back', sklads_path

app/views/sklads/index.html.haml
%h1= t 'sklads'
%table
  %thead
    %tr
      %th= t 'name'
      %th= t 'created_at'
      %th{:colspan => "2"}
  %tbody
    - @sklads.each do |sklad|
      %tr
        %td= sklad.name
        %td= sklad.created_at
        %td= link_to t('show'), sklad
        / %td= link_to 'Edit', edit_sklad_path(region)
        %td= link_to t('destroy'), sklad, method: :delete, data: { confirm: t('you_sure?') }
%br/
= link_to t('new_sklad'), new_sklad_path

app/views/sklads/new.html.haml
%h1= t 'new_sklad'
= render 'form', sklad: @sklad, regions: @regions
= link_to t('back'), sklads_path

app/views/sklads/show.html.haml
/ = link_to t('edit'), edit_sklad_path(@sklad)
/ |
/ = link_to t('back'), sklads_path

= render 'sklads/menu'

%p
  %strong= t('sklad')+":"
  = @sklad.name

= render 'products'