config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :sklads do
    resources :deliveries
  end

  resources :deliveries
  resources :sklad_products
  resources :regions
  resources :products
  resources :transfers
end

app/models/sklad_product.rb
class SkladProduct < ApplicationRecord
  belongs_to :product
  belongs_to :sklad
  
  # delegate :name, to: :product # if get only name of product 
end

app/controllers/sklad_products_controller.rb
class SkladProductsController < ApplicationController
  before_action :set_sklad_product, only: [:show, :edit, :update, :destroy]

  # GET /sklad_products
  def index
    @sklad_products = SkladProduct.all
  end

  # GET /sklad_products/1
  def show
  end

  # GET /sklad_products/new
  def new
    @sklad_product = SkladProduct.new
  end

  # GET /sklad_products/1/edit
  def edit
  end

  # POST /sklad_products
  def create
    @sklad_product = SkladProduct.new(sklad_product_params)

    if @sklad_product #.save
      redirect_to @sklad_product, notice: 'Sklad product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /sklad_products/1
  def update
    if @sklad_product.update(sklad_product_params)
      redirect_to @sklad_product, notice: 'Sklad product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /sklad_products/1
  def destroy
    @sklad_product.destroy
    redirect_to sklad_products_url, notice: 'Sklad product was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sklad_product
      @sklad_product = SkladProduct.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sklad_product_params
      params.require(:sklad_product).permit(:product_id, :sklad_id, :quantify)
    end
end

app/helpers/sklad_products_helper.rb
module SkladProductsHelper
end

app/views/sklad_products/_form.html.haml
= form_for @sklad_product do |f|
  - if @sklad_product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sklad_product.errors.count, "error")} prohibited this sklad_product from being saved:"
      %ul
        - @sklad_product.errors.full_messages.each do |message|
          %li= message
  = f.hidden_field :sklad, value: @sklad.id

  .field
    = render 'products', form: f
  .actions

    = f.submit t('create_delivery')

app/views/sklad_products/edit.html.haml
%h1 Editing sklad_product

= render 'form'

= link_to 'Show', @sklad_product
\|
= link_to 'Back', sklad_products_path

app/views/sklad_products/index.html.haml
%h1 Listing sklad_products

%table
  %thead
    %tr
      %th Product
      %th Sklad
      %th Quantify
      %th
      %th
      %th

  %tbody
    - @sklad_products.each do |sklad_product|
      %tr
        %td= sklad_product.product
        %td= sklad_product.sklad
        %td= sklad_product.quantify
        %td= link_to 'Show', sklad_product
        %td= link_to 'Edit', edit_sklad_product_path(sklad_product)
        %td= link_to 'Destroy', sklad_product, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Sklad product', new_sklad_product_path

app/views/sklad_products/new.html.haml
= render 'sklads/show'

%h1= t 'delivery'

= render 'form'

/ = link_to 'Back', sklad_products_path

app/views/sklad_products/show.html.haml
%p
  %b Product:
  = @sklad_product.product
%p
  %b Sklad:
  = @sklad_product.sklad
%p
  %b Quantify:
  = @sklad_product.quantify

= link_to 'Edit', edit_sklad_product_path(@sklad_product)
\|
= link_to 'Back', sklad_products_path