config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :sklads do
    resources :deliveries
  end

  resources :deliveries
  resources :sklad_products
  resources :regions
  resources :products
  resources :transfers
end

app/models/region.rb
class Region < ApplicationRecord
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  # GET /regions
  def index
    @regions = Region.all
  end

  # GET /regions/1
  def show
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions
  def create
    @region = Region.new(region_params)

    if @region.save
      redirect_to @region, notice: 'Region was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /regions/1
  def update
    if @region.update(region_params)
      redirect_to @region, notice: 'Region was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /regions/1
  def destroy
    @region.destroy
    redirect_to regions_url, notice: 'Region was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def region_params
      params.require(:region).permit(:city, :name, :district, :lat, :lng)
    end
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/regions/_form.html.haml
= form_with(model: region) do |form|
  - if region.errors.any?
    #error_explanation
      %h2
        = pluralize(region.errors.count, "error")
        prohibited this region from being saved:
      %ul
        - region.errors.each do |error|
          %li= error.full_message
  .field
    = form.label :city
    = form.text_field :city
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :district
    = form.text_field :district
  .field
    = form.label :lat
    = form.text_field :lat
  .field
    = form.label :lng
    = form.text_field :lng
  .actions
    = form.submit

app/views/regions/edit.html.haml
%h1 Editing Region
= render 'form', region: @region
= link_to 'Show', @region
|
= link_to 'Back', regions_path

app/views/regions/index.html.haml
%h1 Regions
%table
  %thead
    %tr
      %th City
      %th Name
      %th District
      %th Lat
      %th Lng
      %th{:colspan => "3"}
  %tbody
    - @regions.each do |region|
      %tr
        %td= region.city
        %td= region.name
        %td= region.district
        %td= region.lat
        %td= region.lng
        %td= link_to 'Show', region
        %td= link_to 'Edit', edit_region_path(region)
        %td= link_to 'Destroy', region, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Region', new_region_path

app/views/regions/new.html.haml
%h1 New Region
= render 'form', region: @region
= link_to 'Back', regions_path

app/views/regions/show.html.haml
%p
  %strong City:
  = @region.city
%p
  %strong Name:
  = @region.name
%p
  %strong District:
  = @region.district
%p
  %strong Lat:
  = @region.lat
%p
  %strong Lng:
  = @region.lng
= link_to 'Edit', edit_region_path(@region)
|
= link_to 'Back', regions_path